slam_toolbox:
  ros__parameters:

    # 1. Coordinate Frames & Topics
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan
    mode: mapping # "mapping" or "localization"

    # 2. Robot Specifics (Since we have no wheels, we rely heavily on the laser)
    # If the laser is mounted upside down, change this to true
    transform_timeout: 0.2
    tf_buffer_duration: 30.
    stack_size_to_use: 40000000 # boost program stack size

    # 3. Mapping Behavior
    map_update_interval: 1.0 # Update map every 1 second
    resolution: 0.05 # 5cm grid resolution
    max_laser_range: 20.0 # Max range to trust your sensor (in meters)
    
    # 4. Scan Matching (The "Brain")
    # These control how aggressive the algorithm is
    minimum_time_interval: 0.1
    transform_publish_period: 0.02
    map_start_pose: [0.0, 0.0, 0.0]

    # 5. Processor Settings
    debug_logging: false
    throttle_scans: 1
    
    # 6. Internal Logic (Standard settings)
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG_
    ceres_loss_function: None